apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.Name }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
spec:
  replicas: {{default 1 .Values.Replicas }}
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{ .Values.Name }}"
    spec:
      containers:
      - name: k-client-demo
        resources:
          requests:
            cpu: "{{.Values.CpuRequests}}"
            memory: "{{.Values.MemoryRequests}}"
          limits:
            cpu: "{{.Values.CpuLimits}}"
            memory: "{{.Values.MemoryLimits}}"
        image: "{{ printf "%s:%s" .Values.Image.Name .Values.Image.Tag}}"
        command: ["python", "./client.py","k-demo-server","5000"]
